### ISSUE TITLE
TypeError · Cannot read property 'previousSibling' of null

### ISSUE THREAD

**Issue by sandorvasas** [syncfusion/ej2-react-ui-components#13] opened 2019-04-24 04:52 UTC
Stacktrace:
```
TypeError Cannot read property 'previousSibling' of null 
    bundle.js:9:957440 Function.e.Insert
    bundle.js:9:962432 e.createLink
    bundle.js:9:961681 e.linkCommand
    bundle.js:9:120534 e.notify
    bundle.js:9:921823 e.execCommand
    bundle.js:9:1086574 e.onPaste
    bundle.js:9:120534 e.notify
    bundle.js:9:44109 t.notify
    bundle.js:9:1150900 t.onPaste
```

I traced it back to `node_modules/@syncfusion/ej2-richtexteditor/src/editor-manager/plugin/inserthtml.js`
```
            var preNode = nodeCutter.GetSpliceNode(range, closestParentNode);
            var sibNode = preNode.previousSibling;
            var parentNode = preNode.parentNode;
```
Case: `preNode is null`

There are no UI events reported right before the error, and it's apparently an insertion, so I suppose it happens on CTRL+V

**Comment by AshokkumarBalasubramanian** [comment] 2019-04-26 09:35
Hi @sandorvasas ,

We have checked your reported query. We have tried to replicate the issue on inserting links into Rich Text Editor components using paste action (CTRL + V) and Toolbar icons. But unfortunately, we were unable to reproduce the issue on our end. Can you please share the proper replication procedure for this issue or else, please reproduce your issue on below sample and also share your packages version details?

Sample: https://stackblitz.com/edit/react-5pgv13-pse1ow?file=index.js

Regards,
Ashokkumar B.

**Comment by rajendranr-5483** [comment] 2020-07-21 17:11
@sandorvasas ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns about this requirement.

**Closed** 2020-07-22 04:54 UTC
Labels: need-more-information, rich-text-editor
