### ISSUE TITLE
Selection doesn't persist

### ISSUE THREAD

**Issue by riyasat** [syncfusion/ej2-react-ui-components#140] opened 2023-12-04 15:58 UTC
Hi,
I am using syncfusion grid with remote data. It works fine but the selection with pagination doesn't persist. Here is a demo of the issue.
https://stackblitz.com/edit/react-yrq8rf?file=index.js

If it can be done in another way can you please point me out thanks.

Regards,
Ali

**Comment by riyasat** [comment] 2023-12-06 16:18
Hi,
Thanks for the clarification, all of your provided examples. 
My environment is similar to this custom data binding example. I am loading data with Ajax Call.

When I use that example and if I set isPrimaryKey true it still doesn't persist the selection.

https://stackblitz.com/edit/react-ivdbeg?file=index.js

Can you please help me out here?

**Comment by DineshnarasimmanMSF4057** [comment] 2023-12-08 09:32
We apologize for the trouble you've experienced with our product. Our team has confirmed that the reported behavior is a breaking issue on our end, which we have logged as "**Selection is not persisted when persistSelection is enable with custom Data Binding**". Thank you for taking the time to bring this to our attention. We will include a fix for this issue in the volume 4 release, which is planned for December 15 , 2023.
 
You can easily track the status of your request, review the proposed resolution timeline, and get in touch with us for any additional inquiries by using the following link,
 
Feedback: https://www.syncfusion.com/feedback/49107/selection-is-not-persisted-when-persistselection-is-enable-with-custom-data
 
Disclaimer: "Inclusion of this solution in the weekly release may change due to other factors, including but not limited to QA checks and work reprioritization".

**Comment by rajapandiravi1009** [comment] 2023-12-21 04:59
We are glad to announce that our Essential Studio 2023 Volume 4 release v24.1.41 is rolled out. In this release, we have included the fix for “Selection is not persisted when persistSelection is enable with custom Data Binding” in this version and is available for download under the following link.

Download link: [Essential Studio 2023 Volume 4 Main Release v24.1.41 is available for download | Announcements Forums | Syncfusion](https://www.syncfusion.com/forums/185916/essential-studio-2023-volume-4-main-release-v24-1-41-is-available-for-download)

Sample: https://stackblitz.com/edit/react-ivdbeg-ycpwxp?file=package.json,index.js

Feedback: https://www.syncfusion.com/feedback/49107/selection-is-not-persisted-when-persistselection-is-enable-with-custom-data

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

**Comment by riyasat** [comment] 2023-12-21 07:33
Hi,
Thanks for sharing the update. I am sorry to say but this is still not working properly. 
Here are the step to reproduce:

1. Click on the sample link
2. Select All by clicking on the header checkbox
     - **First issue:** Now try to un select all by click on same check box, It doesn't work
     - **Second issue** Click on the last page button and then pervious button, You will see nothing is selected there
     - **Third issue** Try to add grouping in the columns, now try to select persistent selection will not work

**Comment by DineshnarasimmanMSF4057** [comment] 2023-12-27 12:47
We apologize for the trouble you've experienced with our product. We have confirmed that the reported behavior is an issue from our side and logged it as “**persistSelection issues with custom Data Binding**”. Thank you for taking the time to report this issue and helping us improve our product. At Syncfusion, we are committed to fixing all validated defects (subject to technical feasibility and Product Development Life Cycle) and will include the defect fix in our upcoming patch release which will be rolled out on “January 17, 2024”.
 
You can now track the current status of your request, review the proposed resolution timeline, and contact us for any further inquiries through the below link,
 
Feedback:  https://www.syncfusion.com/feedback/49544/persistselection-issues-with-custom-data-binding
 
Disclaimer: "Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization".

**Comment by DineshnarasimmanMSF4057** [comment] 2024-01-24 09:50
We are glad to announce that, we have included the fix for the issue “persistSelection issues with custom Data Binding” in our 24.1.47 release.  So please upgrade to our latest version of the Syncfusion package to resolve the reported issue.
 
Sample Link: https://stackblitz.com/edit/react-ivdbeg-maqxyr?file=package.json,index.js
 
Feedback: https://www.syncfusion.com/feedback/49544/persistselection-issues-with-custom-data-binding
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

**Comment by gsumankumar** [comment] 2024-02-07 12:56
The reported issue has been successfully addressed in release version 24.1.47. Consequently, we are closing this ticket for administrative purposes. Should you have any additional questions or concerns, please feel free to reopen the ticket, and we will be more than happy to assist you further.

**Closed by gsumankumar** 2024-02-07 12:56 UTC
Labels: component/data-grid
