### ISSUE TITLE
schedule calendar DST issue in recurrent events

### ISSUE THREAD

**Issue by elehaf16** [syncfusion/ej2-react-ui-components#44] opened 2020-02-28 11:54 UTC
For example, you create a recurrent event with this configuration:

![Captura de pantalla 2020-02-27 a las 19 40 36](https://user-images.githubusercontent.com/20958835/75545271-c4c4ba80-5a1d-11ea-8735-cce9cbc56ba6.png)

You set the scheduler timezone to UTC, to see the behaviour, when the serie cross the DST:

[This image display the recurrent event before DST time.]
![Captura de pantalla 2020-02-28 a las 11 20 03](https://user-images.githubusercontent.com/20958835/75545793-25a0c280-5a1f-11ea-9189-7d535578712c.png)

[This image display the recurrent event after DST time.]
![Captura de pantalla 2020-02-28 a las 11 20 14](https://user-images.githubusercontent.com/20958835/75545775-191c6a00-5a1f-11ea-87fe-13c1cc6786ce.png)

So, what we see is that the recurrent events that are generated before DST start at 1:30 pm (UTC) and the event generated after DST start  also at 1:30 pm (UTC), and it should start at 12:30 pm (UTC) or 1:30 (UTC +1), so there is no change from DST time. 

instead if you set the calendar time zone to Canary Island the result is OK.

Other example,  you create a recurrent event with this configuration:

![Captura de pantalla 2020-02-28 a las 11 18 05](https://user-images.githubusercontent.com/20958835/75546206-f8084900-5a1f-11ea-854b-5381fe26cddc.png)

Where Reykjavik timezone hasn't DST CHANGE. If you set the schedule to Canary Island where it has DST CHANGE, the result is also wrong:

![Captura de pantalla 2020-02-28 a las 11 50 54](https://user-images.githubusercontent.com/20958835/75546540-9e544e80-5a20-11ea-8e67-b20efff177b1.png)

Because should be render at 13:00 pm, in Canary Island timezone.

Instead in UTC TIMEZONE the event are rendered correctly.

I think that the problem is that when the recurrent event is generated, the algorithm It does not take into account what time zone the calendar is in, if it has DST or not.

![Captura de pantalla 2020-02-28 a las 12 03 55](https://user-images.githubusercontent.com/20958835/75547279-6f3edc80-5a22-11ea-937a-73d84872d136.png)

we see that the event generated is in GMT +0100 and not in UTC, when the schedule is set in UTC timezone and besides that Reykjavik does not have DST.

**Comment by Balasubramanian-Sattanathan** [comment] 2020-03-10 11:23
We have tried to replicate the reported problem by following the shared replication steps. Since we couldn’t reproduce it at our end. So kindly share your time-zone details to serve you better. 

Online Demos: https://ej2.syncfusion.com/react/demos/#/material/schedule/timezone  

Please let us know if you have any concerns.

**Comment by tonydehnke** [comment] 2020-03-10 12:49
We are seeing some weird issues with events being created and being placed in odd times since the time change as well.

Also seeing 30 minute events being saved as 60 minute events.  All since the time change.

Tony Dehnke

**Comment by elehaf16** [comment] 2020-03-10 21:36
> We have tried to replicate the reported problem by following the shared replication steps. Since we couldn’t reproduce it at our end. So kindly share your time-zone details to serve you better.
> 
> Online Demos: https://ej2.syncfusion.com/react/demos/#/material/schedule/timezone
> 
> Please let us know if you have any concerns.

My timezone is Canary Islands UTC+00:00, that has DST. 

I think that the problem is that using the Date javascript object to generate the events from a recurrent event, the algorithm doesn't take into account the DST if the browser where you are executing the schedule has a timezone where there is DST.

**Comment by tonydehnke** [comment] 2020-03-11 03:16
That is a good point and could be what I am experiencing sometimes too as I am in Thailand now (now DST) and my app/clients are based in North America, most of which has DST.

I was experiencing a pretty consistent issue when testing bookings on Sunday - but only when trying to create an event in certain time blocks.

Tony Dehnke

**Comment by Balasubramanian-Sattanathan** [comment] 2020-03-11 14:24
We have watched your shared video and analyzed the reported problem at our end. We could able to reproduce it. So we logged the below defect report. The fix for this defect will be included in mid of April 2020. We would appreciate your valuable patience until then.

Feedback: https://www.syncfusion.com/feedback/12662/schedule-calendar-dst-issue-in-recurrence-events

**Comment by tonydehnke** [comment] 2020-03-11 14:40
Thanks for the update, but that is an long time for a fix on a calendar issue that relates to actually getting events to show up in the right spots, that is kind of the 1 thing a calendar should do correctly :)

Tony Dehnke

**Comment by elehaf16** [comment] 2020-03-11 16:16
> We have watched your shared video and analyzed the reported problem at our end. We could able to reproduce it. So we logged the below defect report. The fix for this defect will be included in mid of April 2020. We would appreciate your valuable patience until then.
> 
> Feedback: https://www.syncfusion.com/feedback/12662/schedule-calendar-dst-issue-in-recurrence-events
Facing issue with Scheduler while the timezone has DST value. Find the steps to reproduce the issue.

On your feedback, you try to replicate the error with this:

_**Replication steps :

_1. Set system timezone as (UTC +00:00) Dublin, Edinburgh, Lisbon, London.

2. Open schedule sample

(https://ej2.syncfusion.com/react/demos/#/material/schedule/timezone)

3. Open the editor window for March 25th, 2020.

4. Set the start time as 3 PM and endTime as 3.30 PM

5. Check the timezone box

6. Set the "(UTC+00:00) Canary Islands" as StartTimezone and EndTimezone

7. Change the recurrence option to Daily and set count as 8 option

8. The event will be created from March 25th to April 1 (same 3 PM to 3.30 PM)

9. After March 28th, the event should be shown as 2 PM to 2.30 PM (because DST occurs after 28th march)

10. But the events remains the same (i.e 3 to 3.30 PM)**__

I have to make a correction: 

To replicate the error the step 1 should be: 

** 1: Set system timezone AS UTC, for example. 

Because (UTC +00:00) London has the same timezone than Canary Islands, and the error then should not be shown, it only happens when the timezone details is different from the system timezone and event timezone. **

**Comment by VengateshManiraj** [comment] 2020-04-08 10:48
> > We have watched your shared video and analyzed the reported problem at our end. We could able to reproduce it. So we logged the below defect report. The fix for this defect will be included in mid of April 2020. We would appreciate your valuable patience until then.
> > Feedback: https://www.syncfusion.com/feedback/12662/schedule-calendar-dst-issue-in-recurrence-events
> > Facing issue with Scheduler while the timezone has DST value. Find the steps to reproduce the issue.
> 
> On your feedback, you try to replicate the error with this:
> 
> _**Replication steps :
> 
> _1. Set system timezone as (UTC +00:00) Dublin, Edinburgh, Lisbon, London.
> 
> 1. Open schedule sample
> 
> (https://ej2.syncfusion.com/react/demos/#/material/schedule/timezone)
> 
> 1. Open the editor window for March 25th, 2020.
> 2. Set the start time as 3 PM and endTime as 3.30 PM
> 3. Check the timezone box
> 4. Set the "(UTC+00:00) Canary Islands" as StartTimezone and EndTimezone
> 5. Change the recurrence option to Daily and set count as 8 option
> 6. The event will be created from March 25th to April 1 (same 3 PM to 3.30 PM)
> 7. After March 28th, the event should be shown as 2 PM to 2.30 PM (because DST occurs after 28th march)
> 8. But the events remains the same (i.e 3 to 3.30 PM)**__
> 
> I have to make a correction:
> 
> To replicate the error the step 1 should be:
> 
> ** 1: Set system timezone AS UTC, for example.
> 
> Because (UTC +00:00) London has the same DST (they change the summer hour on the same day) than Canary Islands, and the error then should not be shown, it only happens when the DST is different from the system timezone and the event timezone.

Thanks for sharing more details. We will consider your suggestion in this feedback.

**Comment by VengateshManiraj** [comment] 2020-05-15 03:07
We are glad to announce that “Daylight Saving Time for recurrence events” related defects have been resolved in our latest package v18.152. We suggest you please upgrade your package version to the latest to get the solution.

**Comment by rajendranr-5483** [comment] 2020-07-21 16:55
@elehaf16 ,

We have resolved DST related issues in Scheduler already. 

We are closing this thread now. 

Regards,
Rajendran R.

**Closed** 2020-07-22 04:50 UTC
Labels: need-more-information, schedule
