### ISSUE TITLE
export comment text with annotation object

### ISSUE THREAD

**Issue by surajsrivathsa** [syncfusion/ej2-react-ui-components#135] opened 2023-09-14 10:00 UTC
Hello Team,

I have been trying to export annotation object (pdf text, highlight and comment text) with `viewer.exportAnnotationsAsObject()` as mentioned in [https://ej2.syncfusion.com/documentation/pdfviewer/how-to/import-export-annotation-object](url), but the comment text are not getting exported out. However if i post any reply to comment it gets exported. Could you please let me know if it is possible to export comment text as well?

comment text in UI:
![image](https://github.com/syncfusion/ej2-react-ui-components/assets/15963895/b7f8b134-28cb-4787-a016-c104da3abe72)

exported annotation object json:

![image](https://github.com/syncfusion/ej2-react-ui-components/assets/15963895/1ce5895f-7abe-4280-aa82-07fba9b2e173)

**Comment by visvesvar** [comment] 2023-09-25 07:03
Hi,



We have confirmed that the reported issue “Export comment text with annotation object” is a defect and logged the defect reported for the same. The fix for the issue will be included in our upcoming weekly NuGet release on October 11, 2023. You can track the status using the below feedback link.



Feedback link: [ExportAnnotationAsObject is not working even though annotation is present in the sample | Issue Feedback](https://www.syncfusion.com/feedback/47030/exportannotationasobject-is-not-working-even-though-annotation-is-present-in-the)



Disclaimer: “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.”

**Comment by gsumankumar** [comment] 2023-10-03 06:16
For housekeeping purposes, we are closing this ticket. You can track the progress of the reported bug by clicking on the feedback link below [ExportAnnotationAsObject is not working even though annotation is present in the sample | Issue Feedback](https://www.syncfusion.com/feedback/47030/exportannotationasobject-is-not-working-even-though-annotation-is-present-in-the)

**Closed by gsumankumar** 2023-10-03 06:16 UTC
Labels: pdf-viewer
