### ISSUE TITLE
TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by sandorvasas** [syncfusion/ej2-react-ui-components#12] opened 2019-04-24 04:08 UTC
Getting `TypeError: Cannot read property 'contains' of undefined` when clicking `SPAN.e-btn-icon.e-unorder-list.e-icons` (= inserting an unordered list I suppose)

The relevant code piece being reported:
```

length?(c.push(p),p=p.childNodes[0]):p&&("BR"===p.tagName\|\|p.nodeType===Node.TEXT_NODE\|\|p.classList.contains(a.startSelection)\|\|p.classList.contains(a.endSelection))&&o.g.indexOf(p.parentNode.tagName.

```

Stacktrace:
```

TypeError Cannot read property 'contains' of undefined 
    bundle.js:9:943410 e.blockNodes
    bundle.js:9:968949 e.applyListsHandler
    bundle.js:9:120534 e.notify
    bundle.js:9:921502 e.execCommand
    bundle.js:9:1179291 t.e.process
    bundle.js:9:1089366 e.onToolbarClick
    bundle.js:9:120534 e.notify
    bundle.js:9:44109 t.notify
    bundle.js:9:1113430 e.toolbarClick
    bundle.js:9:120534 e.notify

```

I assume you could just patch it by ensuring `p.classList` exists?

**Comment by AshokkumarBalasubramanian** [comment] 2019-04-26 09:14
Hi @sandorvasas ,

We have checked your reported query. We have tried to replicate the issue on selecting text and clicked on unordered list in Rich Text Editor Toolbar icons. But unfortunately, we were unable to reproduce the issue on our end. Can you please share the proper replication procedure for this issue or else, please reproduce your issue on below sample and share your packages version details?

Sample: https://stackblitz.com/edit/react-5pgv13-pse1ow?file=index.js

Regards,
Ashokkumar B(Syncfusion software pvt.ltd).

**Comment by rajendranr-5483** [comment] 2020-07-21 17:12
@sandorvasas ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns about this requirement.

**Closed** 2020-07-22 04:54 UTC
Labels: need-more-information, rich-text-editor
