### ISSUE TITLE
Memory Leaks in Grid

### ISSUE THREAD

**Issue by estebanadams** [syncfusion/ej2-react-ui-components#128] opened 2023-04-06 13:52 UTC
React 18.2.0
"@syncfusion/ej2-react-buttons": "^19.3.44",
"@syncfusion/ej2-react-grids": "20.4.48",
"@syncfusion/ej2-react-inputs": "^19.3.44",
"@syncfusion/ej2-react-navigations": "^19.4.41",

Hello, I'm loading big object (70Mb) in the grid with the dataSource Props and for some reason when I go from grid page to Home then back and forth between 2 page, memory comsumption increase everytime and then crash my tab,

To determine that it was the syncfusion grid components that was faulty I just tested with dataSource={[]} and then with my big object

Version 1 never leaked obv

**Comment by hemanthkumar-syncfusion** [comment] 2023-05-04 07:18
Hi estebanadams,

Thanks for sharing the details.
 
We have confirmed that the reported behavior is an issue from our side and logged it as - “Memory Leaks in Grid with React platform”. Thank you for taking the time to report this issue and helping us improve our product. At Syncfusion, we are committed to fixing all validated defects (subject to technical feasibility and [Product Development Life Cycle](https://www.syncfusion.com/support/product-lifecycle/estudio) ) and will include the defect fix in our upcoming volume release which will be rolled out on June 20, 2023.
 
You can now track the current status of your request, review the proposed resolution timeline, and contact us for any further inquiries through the below link,
 
Feedback:  https://www.syncfusion.com/feedback/43383/memory-leaks-in-grid-with-react-platform
 
Disclaimer: Inclusion of this solution in the release may change due to other factors including but not limited to QA checks and works reprioritization.
 
Regards,
Hemanth Kumar S

**Comment by gsumankumar** [comment] 2023-05-09 07:45
Closing for housekeeping purposes. Further, the reported bug can be tracked through below feedback link,  https://www.syncfusion.com/feedback/43383/memory-leaks-in-grid-with-react-platform

**Closed by gsumankumar** 2023-05-09 07:45 UTC
Labels: component/data-grid

**Comment by estebanadams** [comment] 2023-09-01 09:07
@gsumankumar Hello has this issue been fixed ? this link -> https://www.syncfusion.com/feedback/43383/memory-leaks-in-grid-with-react-platform seems broken for me

**Comment by estebanadams** [comment] 2023-09-04 08:52
@gsumankumar @hemanthkumar-syncfusion @bharathm03 @vijays-git

**Comment by hemanthkumar-syncfusion** [comment] 2023-09-05 13:30
Hi estebanadams,

We appreciate your patience and understanding as we work diligently to resolve the issue you reported. We understand that you are eagerly awaiting the patch to address the matter, and we wanted to provide you with an update regarding the delay.

The complexity of the issue necessitates additional time for our team to design a comprehensive solution that not only addresses the problem you reported but also ensures the stability and performance of our product by checking it in various scenarios. Due to this, we will fix the reported issue with "Memory Leaks in Grid with React platform" and will include the defect fix in our upcoming 2023 Vol 3 release, which is expected to be rolled out in the middle or end of September 2023.

Regards,
Hemanth Kumar S

**Comment by estebanadams** [comment] 2023-09-05 14:06
Hi @hemanthkumar-syncfusion ,thank you for your reply, also please check the event listener and DOM nodes leaks 

Regards,

Esteban
