### ISSUE TITLE
Drag and drop doesn't work if event is taller than the Schedule

### ISSUE THREAD

**Issue by flybayer** [syncfusion/ej2-react-ui-components#22] opened 2019-06-25 15:51 UTC
This is a serious bug for my app. If the event has a long duration such that it's taller than the window height, drag and drop doesn't work. When you try to drag and drop you have no control. Each time it jumps backwards in time a few hours or so.

## Example showing bug
Try to drag and drop the event:
https://stackblitz.com/edit/react-53zse9-6gcpck

**Comment by sellakumark** [comment] 2019-06-27 07:16
Dear Customer, 

Syncfusion greetings.

We could reproduce the reported issue and logged the below bug report. Fix will be included in our upcoming Volume 2, 2019 SP release which is excepted to be roll out by the 2nd week of August 2019.
https://www.syncfusion.com/feedback/7148/drag-and-drop-doesnt-work-if-event-is-taller-than-the-schedule 

Regards,
Karthi

**Comment by tonydehnke** [comment] 2019-06-27 15:39
Hi @sellakumark ,   thanks for verifying the issue and responding.  The timeline of 6 or more weeks to fix a basic core functionality that people expect from a calendar today is far too long.  Can you please escalate this issue with your team to see if a fix can be issued earlier.   Thank you.

**Comment by tonydehnke** [comment] 2019-07-22 22:39
@sellakumark Any more update on a fix for this?

**Comment by tonydehnke** [comment] 2019-07-30 17:13
@sellakumark Can you please update us on progress on this?

**Comment by sellakumark** [comment] 2019-08-01 11:00
@tonydehnke this issue needs to be fix in draggable module. We need some more time to fix this issue and ensure properly from our end. We will provide the fix for the issue in August 14, 2019 weekly release.

**Comment by tonydehnke** [comment] 2019-08-01 15:48
That is disappointing to hear it will still take that long, but thank you for the update.

**Comment by tonydehnke** [comment] 2019-08-21 15:57
We just had another client quit using our app because of this issue.  It has now been almost 2 months since we reported this issue to you guys and still no fix.

Please escalate this with your team.  This is a core and standard function in any calendar today.  This should not be a bug, and it should not take 2 months to fix!!

**Comment by sellakumark** [comment] 2019-10-04 06:31
Hi Tony, 

Fix included in Volume 3, 2019 release (v17.3.0.14) and upgrade your version to avail the fix. Please find the below release notes.
https://ej2.syncfusion.com/react/documentation/release-notes/17.3.14/#schedule (241514)

Regards,
Sella

**Comment by rajendranr-5483** [comment] 2020-07-21 17:00
@tonydehnke ,

We are closing this thread now. Reopen it if you have any concerns.

**Closed** 2020-07-22 04:52 UTC
Labels: bug, schedule
